export const prototypesData = [
  {
    coeff: '123456',
    label: 'Ω',
    id: '123456.Ω',
    x: 0,
    y: 0,
    isPrototype: true,
  },
  { coeff: '15', label: 'C', id: '15.C', x: 1, y: 0, isPrototype: true },
  {
    coeff: '15',
    label: 'C#',
    id: '15.C#',
    x: 0.866,
    y: -0.5,
    isPrototype: true,
  },
  { coeff: '15', label: 'D', id: '15.D', x: 0.5, y: -0.866, isPrototype: true },
  { coeff: '15', label: 'D#', id: '15.D#', x: 0, y: -1, isPrototype: true },
  {
    coeff: '15',
    label: 'E',
    id: '15.E',
    x: -0.5,
    y: -0.866,
    isPrototype: true,
  },
  {
    coeff: '15',
    label: 'F',
    id: '15.F',
    x: -0.866,
    y: -0.5,
    isPrototype: true,
  },
  { coeff: '15', label: 'F#', id: '15.F#', x: -1, y: 0, isPrototype: true },
  { coeff: '15', label: 'G', id: '15.G', x: -0.866, y: 0.5, isPrototype: true },
  {
    coeff: '15',
    label: 'G#',
    id: '15.G#',
    x: -0.5,
    y: 0.866,
    isPrototype: true,
  },
  { coeff: '15', label: 'A', id: '15.A', x: 0, y: 1, isPrototype: true },
  {
    coeff: '15',
    label: 'Bb',
    id: '15.Bb',
    x: 0.5,
    y: 0.866,
    isPrototype: true,
  },
  { coeff: '15', label: 'B', id: '15.B', x: 0.866, y: 0.5, isPrototype: true },
  { coeff: '2', label: 'T_0', id: '2.T_0', x: 1, y: 0, isPrototype: true },
  {
    coeff: '2',
    label: 'T_1',
    id: '2.T_1',
    x: 0.5,
    y: -0.866,
    isPrototype: true,
  },
  {
    coeff: '2',
    label: 'T_2',
    id: '2.T_2',
    x: -0.5,
    y: -0.866,
    isPrototype: true,
  },
  { coeff: '2', label: 'T_3', id: '2.T_3', x: -1, y: 0, isPrototype: true },
  {
    coeff: '2',
    label: 'T_4',
    id: '2.T_4',
    x: -0.5,
    y: 0.866,
    isPrototype: true,
  },
  {
    coeff: '2',
    label: 'T_5',
    id: '2.T_5',
    x: 0.5,
    y: 0.866,
    isPrototype: true,
  },
  { coeff: '3', label: 'C+', id: '3.C+', x: 1, y: 0, isPrototype: true },
  { coeff: '3', label: 'C#+', id: '3.C#+', x: 0, y: -1, isPrototype: true },
  { coeff: '3', label: 'D+', id: '3.D+', x: -1, y: 0, isPrototype: true },
  { coeff: '3', label: 'D#+', id: '3.D#+', x: 0, y: 1, isPrototype: true },
  {
    coeff: '3',
    label: 'H_0,3',
    id: '3.H_0,3',
    x: 0.5,
    y: 0.5,
    isPrototype: true,
  },
  {
    coeff: '3',
    label: 'H_0,1',
    id: '3.H_0,1',
    x: 0.5,
    y: -0.5,
    isPrototype: true,
  },
  {
    coeff: '3',
    label: 'H_1,2',
    id: '3.H_1,2',
    x: -0.5,
    y: -0.5,
    isPrototype: true,
  },
  {
    coeff: '3',
    label: 'H_2,3',
    id: '3.H_2,3',
    x: -0.5,
    y: 0.5,
    isPrototype: true,
  },
  { coeff: '4', label: 'C^o7', id: '4.C^o7', x: 1, y: 0, isPrototype: true },
  {
    coeff: '4',
    label: 'C#^o7',
    id: '4.C#^o7',
    x: -0.5,
    y: -0.866,
    isPrototype: true,
  },
  {
    coeff: '4',
    label: 'D^o7',
    id: '4.D^o7',
    x: -0.5,
    y: 0.866,
    isPrototype: true,
  },
  {
    coeff: '4',
    label: 'O_0,2',
    id: '4.O_0,2',
    x: 0.25,
    y: 0.433,
    isPrototype: true,
  },
  {
    coeff: '4',
    label: 'O_0,1',
    id: '4.O_0,1',
    x: 0.25,
    y: -0.433,
    isPrototype: true,
  },
  {
    coeff: '4',
    label: 'O_1,2',
    id: '4.O_1,2',
    x: -0.5,
    y: 0,
    isPrototype: true,
  },
  { coeff: '5', label: '♮', id: '5.♮', x: 0.267, y: 0.462, isPrototype: true },
  { coeff: '5', label: '♭', id: '5.♭', x: 0, y: -0.533, isPrototype: true },
  {
    coeff: '5',
    label: '2♭',
    id: '5.2♭',
    x: -0.267,
    y: 0.462,
    isPrototype: true,
  },
  {
    coeff: '5',
    label: '3♭',
    id: '5.3♭',
    x: 0.462,
    y: -0.267,
    isPrototype: true,
  },
  { coeff: '5', label: '4♭', id: '5.4♭', x: -0.533, y: 0, isPrototype: true },
  {
    coeff: '5',
    label: '5♭',
    id: '5.5♭',
    x: 0.462,
    y: 0.267,
    isPrototype: true,
  },
  {
    coeff: '5',
    label: '6♯',
    id: '5.6♯',
    x: -0.267,
    y: -0.462,
    isPrototype: true,
  },
  { coeff: '5', label: '5♯', id: '5.5♯', x: 0, y: 0.533, isPrototype: true },
  {
    coeff: '5',
    label: '4♯',
    id: '5.4♯',
    x: 0.267,
    y: -0.462,
    isPrototype: true,
  },
  {
    coeff: '5',
    label: '3♯',
    id: '5.3♯',
    x: -0.462,
    y: 0.267,
    isPrototype: true,
  },
  { coeff: '5', label: '2♯', id: '5.2♯', x: 0.533, y: 0, isPrototype: true },
  {
    coeff: '5',
    label: '♯',
    id: '5.♯',
    x: -0.462,
    y: -0.267,
    isPrototype: true,
  },
  { coeff: '6', label: 'WT_1', id: '6.WT_1', x: 1, y: 0, isPrototype: true },
  { coeff: '6', label: 'WT_2', id: '6.WT_2', x: -1, y: 0, isPrototype: true },
];
